In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Loding Excel Workbook

In [2]:
file_path = "../data/raw_data/EduPro Online Platform.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['Users', 'Teachers', 'Courses', 'Transactions']

## Loading Excel Sheets

In [3]:
users = pd.read_excel(file_path, sheet_name="Users")
teachers = pd.read_excel(file_path, sheet_name="Teachers")
courses = pd.read_excel(file_path, sheet_name="Courses")
transactions = pd.read_excel(file_path, sheet_name="Transactions")

## Checking the Size of Each Datasets

In [4]:
print("Users:", users.shape)
print("Teachers:", teachers.shape)
print("Courses:", courses.shape)
print("Transactions:", transactions.shape)

Users: (3000, 5)
Teachers: (60, 7)
Courses: (60, 8)
Transactions: (10000, 7)

## Inspect the Users data

In [5]:
users.head()

   UserID        UserName  Age  Gender                             Email
0  U00001    wilsonjordan   15    Male            patricia27@hotmail.com
1  U00002        angela22   29  Female             hallrandy@hotmail.com
2  U00003  morrisonamanda   33  Female               ganderson@yahoo.com
3  U00004       fthornton   23  Female  christensencatherine@outlook.com
4  U00005  fostergeoffrey   21    Male            karenfuentes@yahoo.com

In [6]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UserID    3000 non-null   str
 1   UserName  3000 non-null   str
 2   Age       3000 non-null   int64
 3   Gender    3000 non-null   str
 4   Email     3000 non-null   str
dtypes: int64(1), str(4)
memory usage: 239.5 KB

In [7]:
users.describe()

               Age
count  3000.000000
mean     24.974333
std       6.046475
min      15.000000
25%      20.000000
50%      25.000000
75%      30.000000
max      35.000000

## Inspect the Teachers data

In [8]:
teachers.head()

,TeacherID,TeacherName,Age,Gender,Expertise,YearsOfExperience,TeacherRating
0,TC00001,Leonard Montgomery,44,Female,Cybersecurity,6,3.24
1,TC00002,Jill Day,32,Female,Digital Marketing,9,4.14
2,TC00003,Amber Torres,32,Male,Design,4,1.56
3,TC00004,Kristi Scott,34,Female,Machine Learning,9,4.39
4,TC00005,David Williams,34,Male,Finance,2,3.11

In [9]:
teachers.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TeacherID          60 non-null     str
 1   TeacherName        60 non-null     str
 2   Age                60 non-null     int64
 3   Gender             60 non-null     str
 4   Expertise          60 non-null     str
 5   YearsOfExperience  60 non-null     int64
 6   TeacherRating      60 non-null     float64
dtypes: float64(1), int64(2), str(4)
memory usage: 5.7 KB

In [10]:
teachers.describe()

             Age  YearsOfExperience  TeacherRating
count  60.000000          60.000000      60.000000
mean   38.450000           6.283333       3.125000
std     7.703015           4.715972       0.949797
min    27.000000           1.000000       1.050000
25%    32.000000           3.000000       2.487500
50%    36.500000           6.000000       3.275000
75%    46.250000           8.000000       3.827500
max    50.000000          24.000000       4.970000

## Inspect the Courses data

In [11]:
courses.head()

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28

In [12]:
courses.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CourseID        60 non-null     str
 1   CourseName      60 non-null     str
 2   CourseCategory  60 non-null     str
 3   CourseType      60 non-null     str
 4   CourseLevel     60 non-null     str
 5   CoursePrice     60 non-null     float64
 6   CourseDuration  60 non-null     float64
 7   CourseRating    60 non-null     float64
dtypes: float64(3), str(5)
memory usage: 6.9 KB

In [13]:
courses.describe()

       CoursePrice  CourseDuration  CourseRating
count    60.000000       60.000000     60.000000
mean     92.986333       27.632500      3.097833
std     153.601506       16.092578      1.171232
min       0.000000        1.200000      1.130000
25%       0.000000       14.500000      2.107500
50%       0.000000       28.505000      3.065000
75%     133.615000       43.012500      4.102500
max     490.900000       49.730000      4.940000

## Inspect the Transactions data

In [14]:
transactions.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042

In [15]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10000 non-null  str
 1   UserID           10000 non-null  str
 2   CourseID         10000 non-null  str
 3   TransactionDate  10000 non-null  datetime64[us]
 4   Amount           10000 non-null  float64
 5   PaymentMethod    10000 non-null  str
 6   TeacherID        10000 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 908.0 KB

In [16]:
transactions.describe()

                  TransactionDate        Amount
count                       10000  10000.000000
mean   2025-07-01 03:50:32.640000     91.132347
min           2025-01-01 00:00:00      0.000000
25%           2025-04-02 00:00:00      0.000000
50%           2025-06-30 00:00:00      0.000000
75%           2025-09-28 00:00:00    119.040000
max           2025-12-30 00:00:00    490.900000
std                           NaN    152.063524

In [17]:
transactions["TransactionDate"].min()

Timestamp('2025-01-01 00:00:00')

In [18]:
transactions["TransactionDate"].max()

Timestamp('2025-12-30 00:00:00')

In [19]:
transactions["TransactionDate"].head()

0   2025-10-25
1   2025-01-13
2   2025-03-28
3   2025-06-02
4   2025-08-10
Name: TransactionDate, dtype: datetime64[us]

## Checking Data Types

In [20]:
users.dtypes

UserID        str
UserName      str
Age         int64
Gender        str
Email         str
dtype: object

In [21]:
teachers.dtypes

TeacherID                str
TeacherName              str
Age                    int64
Gender                   str
Expertise                str
YearsOfExperience      int64
TeacherRating        float64
dtype: object

In [22]:
courses.dtypes

CourseID              str
CourseName            str
CourseCategory        str
CourseType            str
CourseLevel           str
CoursePrice       float64
CourseDuration    float64
CourseRating      float64
dtype: object

In [23]:
transactions.dtypes

TransactionID                 str
UserID                        str
CourseID                      str
TransactionDate    datetime64[us]
Amount                    float64
PaymentMethod                 str
TeacherID                     str
dtype: object

## Checking IDs

In [24]:
print("Unique Users:", users["UserID"].nunique())
print("Unique Teachers:", teachers["TeacherID"].nunique())
print("Unique Courses:", courses["CourseID"].nunique())
print("Transactions:", transactions["TransactionID"].nunique())

Unique Users: 3000
Unique Teachers: 60
Unique Courses: 60
Transactions: 10000

## Checking Categories

In [25]:
courses["CourseCategory"].value_counts()

CourseCategory
Programming                5
Design                     5
Business                   5
Marketing                  5
Data Science               5
Machine Learning           5
Cybersecurity              5
Project Management         5
Finance                    5
Artificial Intelligence    5
Web Development            5
Digital Marketing          5
Name: count, dtype: int64

In [26]:
courses["CourseLevel"].value_counts()

CourseLevel
Beginner        21
Advanced        21
Intermediate    18
Name: count, dtype: int64

In [27]:
courses["CourseType"].value_counts()

CourseType
Free    38
Paid    22
Name: count, dtype: int64

In [28]:
teachers["Expertise"].value_counts()

Expertise
Digital Marketing          11
Cybersecurity               9
Finance                     6
Artificial Intelligence     6
Machine Learning            5
Data Science                5
Project Management          5
Web Development             5
Design                      4
Business                    2
Marketing                   1
Programming                 1
Name: count, dtype: int64

In [29]:
transactions["PaymentMethod"].value_counts()

PaymentMethod
PayPal           3389
Credit Card      3333
Bank Transfer    3278
Name: count, dtype: int64

## Checking Missing Values

In [30]:
users.isnull().sum()

UserID      0
UserName    0
Age         0
Gender      0
Email       0
dtype: int64

In [31]:
teachers.isnull().sum()

TeacherID            0
TeacherName          0
Age                  0
Gender               0
Expertise            0
YearsOfExperience    0
TeacherRating        0
dtype: int64

In [32]:
courses.isnull().sum()

CourseID          0
CourseName        0
CourseCategory    0
CourseType        0
CourseLevel       0
CoursePrice       0
CourseDuration    0
CourseRating      0
dtype: int64

In [33]:
transactions.isnull().sum()

TransactionID      0
UserID             0
CourseID           0
TransactionDate    0
Amount             0
PaymentMethod      0
TeacherID          0
dtype: int64

## Checking Duplicate Records

In [34]:
print("Duplicate Users:", users.duplicated().sum())
print("Duplicate Teachers:", teachers.duplicated().sum())
print("Duplicate Courses:", courses.duplicated().sum())
print("Duplicate Transactions:", transactions.duplicated().sum())

Duplicate Users: 0
Duplicate Teachers: 0
Duplicate Courses: 0
Duplicate Transactions: 0